# This workflow is used to terminate an existing EC2 instance

name: Terminate EC2 instance

on:
  workflow_dispatch:
    workflows: ["ec2create.yml"]
    types:
      - completed

jobs:
  terminate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Download EC2 instance ID artifact
        uses: actions/download-artifact@v2
        with:
          name: ec2-instance-id
          path: /tmp

      - name: Configure AWS credentials for EC2 termination
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Read EC2 instance ID from artifact
        run: |
          # Read the EC2 instance ID from the file
          instance_id=$(cat /tmp/ec2-instance-id/ec2-instance-id.txt)

          if [[ -n "$instance_id" ]]; then
            aws ec2 terminate-instances --instance-ids $instance_id
          else
            echo "EC2 instance ID not found."
          fi
