# This workflow is used to terminate an existing EC2 instance

name: Terminate EC2 instance

on:
  workflow_dispatch:
    workflows: ["ec2create.yml"]
    types:
      - completed

jobs:
  terminate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for EC2 termination
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get EC2 instance ID
        id: ec2
        run: |
          # Use the AWS CLI to get the EC2 instance ID based on your filtering criteria
          instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=github_wf_${{ github.event.inputs.ec2_name }}" --query "Reservations[0].Instances[0].InstanceId" --output text)
          echo "::set-output name=instance_id::$instance_id"

      - name: Terminate EC2 instance
        if: steps.ec2.outputs.instance_id != ''
        run: |
          # Use the instance_id variable from the previous step to terminate the EC2 instance
          aws ec2 terminate-instances --instance-ids ${{ steps.ec2.outputs.instance_id }}

