# Name of Action
name: shutdown

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'Enter instance_id of the EC2 to terminate'
        required: true
  # If you want to trigger this on push to a branch uncomment below
  # push:
  #  branches: [ main ]
  
  # This allows you to run this workflow manually from the Actions tab
 env:
   AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Below this are each of the steps that are run
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

      - name: Terminate EC2 instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ inputs.instance_id }} --region ${{ env.AWS_REGION }}
      # Name of step
      # - name: Stop AWS EC2
      #   # Run AWS Command on the GitHub Hosted runner which stops the instance using AWS authentication stored in GitHub Secrets (see below how to add)
      #   run: |
      #     aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}